# Generated by Django 5.0.1 on 2024-04-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(default='NOT STARTED', max_length=50),
        ),
    ]
